name: Greeter workflow
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: Geotilackonish
